### ISSUE TITLE
Console Errors on Player Join

### ISSUE THREAD

**Issue by codeturtle00** [ericgrandt/TotalEconomy#363]
Sponge Version:  1.12.2-2825-7.1.6
Forge Version:  2838
Total Economy Version:  1.8.1

### Description of issue
These may be 3 seperate issues, but all related to player connection.

1. On Player join, console will most of the time log a connection leak: https://pastebin.com/71P1N9S2

2. On player's first-join, there will be warnings of "Unknown column 'staff_balance' in 'field list'": https://pastebin.com/k7UMYAGg

3. I'm unsure what this is, but pretty sure it's been crashing my server at least once a day (this pastebin is a continuation of the last one): https://pastebin.com/YYBL3EKX

**Comment by MarkL4YG** [comment]
1. Not sure about that one. Might be true but is normally not that much of an issue since regular restarts are recommended for MC servers anyways.

2. That is because TE is currently not designed to automatically update your database when new currencies are registered. You can manually create a clone of the ``dollar_balance`` column and name it ``staff_balance`` and this will be resolved.

3. That is probably caused by the connection leak. When connections are leaked, at some point there are not connections left in the pool. Adjusting the pool size or just restarting more frequently will mitigate this issue. However, a fix needs to be implemented on TEs side.

All things aside, I am not sure whether or not @Erigitic will resume development on TotalEconomy any time soon. And my time as an active code-contributor is currently frozen too since my community no longer hosts MC servers. I would assist with any questions though.

**Comment by Erigitic** [comment]
I'm working full time so I don't have much time to work on Total Economy at the moment. But I would like to eventually get back to it and start fixing up all of the breaking issues such as the connection leak and the automatic updating of the database, which should address all of the issues you've outlined above. And @MarkL4YG, I appreciate you assisting people with this issue, along with all of the other issues.
