### ISSUE TITLE
Jobs not working

### ISSUE THREAD

**Issue by ughary** [ericgrandt/TotalEconomy#417]
I installed this plugin through Spigot and /jobs is not working. Jobs are enabled on the configs page, it is set to true. Is there anything I can do to try to fix this?

![Minecraft 6_22_2024 4_56_46 AM](https://github.com/ericgrandt/TotalEconomy/assets/173547340/4d96148f-f09f-4791-9a3e-f0068545e0de)

**Comment by ericgrandt** [comment]
Hi @ughary, `/job` is the right command and it looks like it's working (as in it doesn't error out when running it), though it's not displaying anything. Is that correct? Are you running the command through chat as a player or are you using some other plugin to execute the command? Looks like you're using a non-standard way of executing those commands.

**Comment by ughary** [comment]
It is not displaying anything. I am new to plugins so I am not sure if I needed to do anything after getting it in my server. I am able to use balance and pay other players, but the /job command isn't working. I am running the command through chat as a player and not some other plugin. How do I use a standard way of executing those commands?

**Comment by ericgrandt** [comment]
The chatbox looks different then I'm use to, though doesn't seem like that matters since the other commands are working; which is a good sign. A few other questions just to make sure we have a full picture:

1. Any console errors?
2. Which version of Total Economy? The latest (0.12.1)?
3. Which version of Spigot?
4. What does your config.yml look like under `plugins/TotalEconomy/config.yml`? **VERY IMPORTANT: REMOVE DATABASE INFORMATION BEFORE SENDING**

From what I can tell from testing on my end, when the job feature is disabled you'll end up seeing what's in your picture (the command displays in the chat but it doesn't actually execute anything). Might simply be something misconfigured in your config.yml file.

**Comment by ughary** [comment]
1. No console errors, when I type job in console it shows up as:
23.06 06:30:51 [Server] Server thread/INFO /job
23.06 06:30:51 [Multicraft] ughAry ran command: job
2. Yes, 0.12.1 (April 26th)
3. Spigot 1.21 (latest)
4. Under database, it says Features and then jobs: true. True is in purple. That's all.

**Comment by ericgrandt** [comment]
I'll try testing it with the above versions you provided tomorrow.

In the meantime, is it "Features" or "features" that you have? Make sure it looks something like this:

```
database:
    url: jdbc:mysql://localhost:3306/totaleconomy
    user: root
    password: password
features:
    jobs: true
```

**Comment by ughary** [comment]
user: root
    password: password
features:
    jobs: true
    
    Yes it's exactly the same

**Comment by ughary** [comment]
I have essentialsX plugin and vault

**Comment by ericgrandt** [comment]
> 1. No console errors, when I type job in console it shows up as:
>    23.06 06:30:51 [Server] Server thread/INFO /job
>    23.06 06:30:51 [Multicraft] ughAry ran command: job
> 2. Yes, 0.12.1 (April 26th)
> 3. Spigot 1.21 (latest)
> 4. Under database, it says Features and then jobs: true. True is in purple. That's all.

Haven't had the chance to test this with the above versions on my end yet, though another thing to note is that 0.12.1 is not tested on versions after 1.20.4..

**Comment by ericgrandt** [comment]
Hey @ughary, was able to test some stuff on my end. First of all, Total Economy 0.12.1 does not support Bukkit/Spigot/Paper 1.21; 1.20.4 is the highest version supported currently. Attempting to launch Total Economy 0.12.1 against 1.21 led to some issues, which is expected.

I think the reasons the `balance` and `pay` commands work is because those are also EssentialsX commands as they provide an economy implementation of their own. If you downgrade to 1.20.4 and remove EssentialsX (or disable the economy portion of EssentialsX), you shouldn't encounter any issues. I realize Essentials also provides tons of other useful commands, though I have no experience with that plugin so I'd recommend reaching out to them and asking how to handle compatibility between their plugin and other economy plugins like Total Economy; they probably have something on their wiki. I assume they have a configuration option to allow compatibility with other economy plugins.

Let me know if the downgrading to 1.20.4 and disabling the conflicting EssentialsX functionality works. Thanks.

**Comment by ughary** [comment]
I changed the version, but I can't disable economy in EssentialsX. I can't remove EssentialsX because of their other features so I reached out to them and see if I could use another plugin's (TotalEconomy) economy instead. Thank you for your help!

**Comment by ericgrandt** [comment]
Going to close for now. Please feel free to reopen if necessary. Thanks.
